name: Build and Release new docker images
on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read
  actions: read
  checks: write
  packages: write

jobs:
  build:
    name: Build and Release Docker host
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push zScanner Docker Host
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/bw-zuni-docker-host:latest

